# Dependencies
highlighter:      pygments

gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title: Webdev Hints
tagline: Webdev Hints
description: Personal blog about random web development stuff
url: http://binary-data.github.io
paginate: 10
baseurl: ""
excerpt_separator:   "<!-- more -->"
